name: Docker Publish

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: eibrahim/fluid-calendar

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-arm64:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest-arm64,enable={{is_default_branch}}
            type=ref,event=branch,suffix=-arm64
            type=ref,event=pr,suffix=-arm64
            type=semver,pattern={{version}}-arm64
            type=semver,pattern={{major}}.{{minor}}-arm64
            type=sha,suffix=-arm64

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  create-manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          # Enable experimental features for docker
          mkdir -p ~/.docker
          echo '{"experimental": "enabled"}' > ~/.docker/config.json

          # For main branch or latest tag
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Create a new manifest without dependencies - full specifiers
            IMAGE_AMD64="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@$(docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --format '{{index .RepoDigests 0}}' | cut -d'@' -f2)"
            IMAGE_ARM64="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@$(docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-arm64 --format '{{index .RepoDigests 0}}' | cut -d'@' -f2)"
            
            # Create a new manifest with digests
            docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-new \
              $IMAGE_AMD64 \
              $IMAGE_ARM64
            
            # Annotate the manifest with platform information
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-new \
              $IMAGE_AMD64 --os linux --arch amd64
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-new \
              $IMAGE_ARM64 --os linux --arch arm64
            
            # Push the manifest
            docker manifest push --purge ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-new
            
            # Rename the manifest
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-new ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          fi

          # For tags (releases)
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            
            # Create a new manifest without dependencies - full specifiers
            IMAGE_AMD64="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@$(docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION} --format '{{index .RepoDigests 0}}' | cut -d'@' -f2)"
            IMAGE_ARM64="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@$(docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}-arm64 --format '{{index .RepoDigests 0}}' | cut -d'@' -f2)"
            
            # Create a new manifest with digests for version tag
            docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}-new \
              $IMAGE_AMD64 \
              $IMAGE_ARM64
            
            # Annotate the manifest
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}-new \
              $IMAGE_AMD64 --os linux --arch amd64
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}-new \
              $IMAGE_ARM64 --os linux --arch arm64
            
            # Push the manifest
            docker manifest push --purge ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}-new
            
            # Rename the manifest
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}-new ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
            
            # Process major.minor tag
            MAJOR_MINOR=$(echo ${VERSION} | cut -d. -f1,2)
            
            # Create a new manifest with digests for major.minor tag
            docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${MAJOR_MINOR}-new \
              $IMAGE_AMD64 \
              $IMAGE_ARM64
            
            # Annotate the manifest
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${MAJOR_MINOR}-new \
              $IMAGE_AMD64 --os linux --arch amd64
            docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${MAJOR_MINOR}-new \
              $IMAGE_ARM64 --os linux --arch arm64
            
            # Push the manifest
            docker manifest push --purge ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${MAJOR_MINOR}-new
            
            # Rename the manifest
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${MAJOR_MINOR}-new ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${MAJOR_MINOR}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${MAJOR_MINOR}
          fi
